SHOW API INTEGRATIONS;

GRANT USAGE ON INTEGRATION AAAAAAAAAA TO ROLE TEST_DEV_USER;


GRANT ALL ON SCHEMA TASTY_BYTES_DBT_DB.PUBLIC TO ROLE TASTY_BYTES_DBT_DB_RW;

GRANT MODIFY LOG LEVEL ON ACCOUNT TO ROLE TEST_DEV_USER;

GRANT MODIFY TRACE LEVEL ON ACCOUNT TO ROLE TEST_DEV_USER;

GRANT MODIFY METRIC LEVEL ON ACCOUNT TO ROLE TEST_DEV_USER;

GRANT CREATE DBT PROJECT ON SCHEMA TASTY_BYTES_DBT_DB.DEV TO ROLE TEST_DEV_USER;

GRANT CREATE DBT PROJECT ON SCHEMA my_database.my_schema TO ROLE my_role

SELECT CURRENT_ROLE();

SHOW GRANTS ON SCHEMA TASTY_BYTES_DBT_DB.DEV;

SHOW DATABASE ROLES IN DATABASE TASTY_BYTES_DBT_DB;